version: "3.9"

services:
  backend:
    image: kalyansagar7008/skillproof-backend:latest
    container_name: skillproof-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: kalyansagar7008/skillproof-frontend:latest
    container_name: skillproof-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
