name: CI â€“ Dockerized FastAPI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build image (no push yet)
      - name: Build backend image
        run: |
          docker build -t skillproof-backend:ci ./Backend

      # Run tests inside container
      - name: Run tests
        run: |
          docker run --rm skillproof-backend:ci pytest app
      
      # Login ONLY on main branch
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push ONLY on main branch
      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag skillproof-backend:ci ${{ secrets.DOCKER_USERNAME }}/skillproof-app:latest
          docker tag skillproof-backend:ci ${{ secrets.DOCKER_USERNAME }}/skillproof-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/skillproof-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/skillproof-app:${{ github.sha }}