name: CI â€“ Dockerized SkillProof App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # BACKEND

      - name: Build backend image
        run: |
          docker build -t skillproof-backend:ci ./Backend

      - name: Run backend tests
        run: |
          docker run --rm skillproof-backend:ci pytest

      # FRONTEND

      - name: Build frontend image
        run: |
          docker build -t skillproof-frontend:ci ./Frontend

      # DOCKER HUB LOGIN (main only)
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # PUSH IMAGES (main only)
      - name: Push backend image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag skillproof-backend:ci ${{ secrets.DOCKER_USERNAME }}/skillproof-backend:latest
          docker tag skillproof-backend:ci ${{ secrets.DOCKER_USERNAME }}/skillproof-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/skillproof-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/skillproof-backend:${{ github.sha }}

      - name: Push frontend image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag skillproof-frontend:ci ${{ secrets.DOCKER_USERNAME }}/skillproof-frontend:latest
          docker tag skillproof-frontend:ci ${{ secrets.DOCKER_USERNAME }}/skillproof-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/skillproof-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/skillproof-frontend:${{ github.sha }}
